defaults: &default
  twilio_account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
  twilio_number: <%= ENV['TWILIO_NUMBER'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default